services:
  backend:
    image: registry.gabrielkaszewski.dev/k-notes:latest
    environment:
      - DATABASE_URL=sqlite:///app/data/notes.db
      - JWT_SECRET=change-me
      - JWT_ISSUER=https://idm.gabrielkaszewski.dev/oauth/v2/keys
      - CORS_ORIGINS=https://knotes.gabrielkaszewski.dev
      - HOST=0.0.0.0
      - PORT=3000
      - ALLOW_REGISTRATION=false
    volumes:
      - ./data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.knotes.rule=Host(`knotes.gabrielkaszewski.dev`) || Host(`api.knotes.gabrielkaszewski.dev`)"
      - "traefik.http.routers.knotes.entrypoints=websecure"
      - "traefik.http.routers.knotes.tls.certresolver=letsencrypt"
      - "traefik.http.services.knotes.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
