[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[features]
default = []
jwt = ["dep:jsonwebtoken"]
oidc = ["dep:openidconnect", "dep:reqwest"]

[dependencies]
domain = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
argon2 = "0.5"
url = "2"

jsonwebtoken = { version = "10", features = ["rust_crypto"], optional = true }
openidconnect = { version = "4", optional = true }
reqwest = { version = "0.12", features = ["json"], optional = true }

[dev-dependencies]
tokio = { workspace = true }
